on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2 

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Frontend
      run: docker build -f Dockerfile.frontend -t keshus37/portfolio-frontend .

    - name: Push Frontend
      run: docker push keshus37/portfolio-frontend

    - name: Build Backend
      run: docker build -f Dockerfile.backend -t keshus37/portfolio-backend .

    - name: Push Backend
      run: docker push keshus37/portfolio-backend

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  

      - name: Sync website to S3
        run: aws s3 sync ./frontend s3://portfolio-12345 --exclude ".git/" --exclude ".github/" --delete


  
      
